
const elementosVista = [
    
    'rol_menu',
    'permisos_menu',
    'usuario_menu',
    'unidad_medida_menu',
    'estatus_menu',
    'menu_menu',
    'centroControl_menu',
    'monitor_menu',
    'monitor_corta_menu',
    'producto_menu',
    'producto_variedades_menu',
    'producto_productos_menu',
    'producto_variedadesDeProducto_menu',
    'producto_tiposDeProducto_menu',
    'producto_tiposDeUnidades_menu',
    'producto_tiposDeEmpaque_menu',
    'comercial_menu',
    'comercial_ofertasDeProducto_menu',
    'comercial_solicitudesDeClientes_menu',
    'comercial_clientes_menu',
    'comercial_despachos_menu',
    'produccion_menu',
    'produccion_lotesParaCultivo_menu',
    'produccion_vehiculos_menu',
    'produccion_programacionDeLotes_menu',
    'configuracionDePagos_menu',
    'configuracionDePagos_tiposDePago_menu',
    'configuracionDePagos_tiposDePago_menu',
    'configuracionDePagos_tarifasPorTarea_menu',
    'configuracionDePagos_tarifasPorLabores_menu',
    'configuracionDePagos_periodosDePago_menu',
    'configuracionDePagos_calendarios_menu',
    'configuracionDePagos_centrosDeTrabajo_menu',
    'configuracionDePagos_cargos_menu',
    'configuracionDePagos_empleados_menu',
    'liquidacion_nomina_menu',
    'liquidacionDeNomina_planeacionDiaria_menu',
    'liquidacionDeNomina_trabajosDeCorta_menu',
    'liquidacionDeNomina_trasladoAPrefrio_menu',
    'liquidacionDeNomina_trabajosDeSeleccion_menu',
    'liquidacionDeNomina_laboresDeContratista_menu',
    'liquidacionDeNomina_descuentosDeNomina_menu',
    'administracion_menu',
    'administracion_empresa_menu',
    'administracion_fincas_menu',
    'sistema_menu',
    'sistema_usuarios_menu',
    'sistema_roles_menu',
    'sistema_permisos_menu',
    'sistema_estadoDeRegistros_menu'
  ];
  
  export default elementosVista;
  