// nombre-del-archivo.js

const elementosVista = [
    
    'rol_vista',
    'permisos_vista',
    'usuario_vista',
    'unidad_medida_vista',
    'estatus_vista',
    'menu_vista',
    'centroControl_vista',
    'monitor_vista',
    'monitor_corta_vista',
    'producto_vista',
    'producto_variedades_vista',
    'producto_productos_vista',
    'producto_variedadesDeProducto_vista',
    'producto_tiposDeProducto_vista',
    'producto_tiposDeUnidades_vista',
    'producto_tiposDeEmpaque_vista',
    'comercial_vista',
    'comercial_ofertasDeProducto_vista',
    'comercial_solicitudesDeClientes_vista',
    'comercial_clientes_vista',
    'comercial_despachos_vista',
    'produccion_vista',
    'produccion_lotesParaCultivo_vista',
    'produccion_vehiculos_vista',
    'produccion_programacionDeLotes_vista',
    'configuracionDePagos_vista',
    'configuracionDePagos_tiposDePago_vista',
    'configuracionDePagos_tiposDePago_vista',
    'configuracionDePagos_tarifasPorTarea_vista',
    'configuracionDePagos_tarifasPorLabores_vista',
    'configuracionDePagos_periodosDePago_vista',
    'configuracionDePagos_calendarios_vista',
    'configuracionDePagos_centrosDeTrabajo_vista',
    'configuracionDePagos_cargos_vista',
    'configuracionDePagos_empleados_vista',
    'liquidacion_nomina_vista',
    'liquidacionDeNomina_planeacionDiaria_vista',
    'liquidacionDeNomina_trabajosDeCorta_vista',
    'liquidacionDeNomina_trasladoAPrefrio_vista',
    'liquidacionDeNomina_trabajosDeSeleccion_vista',
    'liquidacionDeNomina_laboresDeContratista_vista',
    'liquidacionDeNomina_descuentosDeNomina_vista',
    'administracion_vista',
    'administracion_empresa_vista',
    'administracion_fincas_vista',
    'sistema_vista',
    'sistema_usuarios_vista',
    'sistema_roles_vista',
    'sistema_permisos_vista',
    'sistema_estadoDeRegistros_vista'
  ];
  
  export default elementosVista;
  