apiVersion: v1
kind: Service
metadata:
  name: agro-online-service
spec:
  type: NodePort
  selector:
    app: agro-online
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
