name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub 
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: byepesg/agro_online
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


# Commenting out the entire deploy job

# deploy:
#   # Define the deploy job that depends on the successful completion of the push_to_registry job
#   needs: push_to_registry
#   runs-on: ubuntu-latest

#   steps:
#     - name: Install doctl
#       # Use the doctl action to install DigitalOcean's command line interface
#       uses: digitalocean/action-doctl@v2
#       with:
#         # Authenticate doctl using the DigitalOcean access token stored in secrets
#         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

#     - name: SSH into Droplet and Deploy
#       # SSH into the Droplet and execute the deployment commands
#       run: |
#         # Connect to the Droplet using SSH; disable strict host key checking for automation
#         ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
#           # Pull the latest Docker image from Docker Hub
#           docker pull byepesg/agro_online:main
          
#           # Stop the running container if it exists
#           docker stop your_container_name || true
          
#           # Remove the existing container to avoid conflicts
#           docker rm your_container_name || true
          
#           # Run the new container with the pulled image on the specified ports
#           docker run -d --name your_container_name -p 9001:8080 byepesg/agro_online:main
#         EOF


