name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub 
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: byepesg/agro_online
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to DigitalOcean Droplet
    needs: push_to_registry
    runs-on: ubuntu-latest
  
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deployment_basil
          chmod 600 ~/.ssh/deployment_basil
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
  
      - name: SSH into Droplet and Deploy
        run: |
          ssh -i ~/.ssh/deployment_basil root@${{ secrets.DROPLET_IP }} << 'EOF'
            docker pull byepesg/agro_online:main
            docker stop your_container_name || true
            docker rm your_container_name || true
            docker run -d --name your_container_name -p 9001:8080 byepesg/agro_online:main
          EOF
  
